# Generated by Django 3.1.6 on 2021-08-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_choice_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=100),
            preserve_default=False,
        ),
    ]
